// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=ip4 -id ply -d VecType=ply_vec -d Type=ply -d Data=plys github.com/platinasystems/go/elib/vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package ip4

import (
	"github.com/platinasystems/go/elib"
)

type ply_vec []ply

func (p *ply_vec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]ply, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *ply_vec) validate(new_len uint, zero ply) *ply {
	c := elib.Index(cap(*p))
	lʹ := elib.Index(len(*p))
	l := elib.Index(new_len)
	if l <= c {
		// Need to reslice to larger length?
		if l > lʹ {
			*p = (*p)[:l]
			for i := lʹ; i < l; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *ply_vec) validateSlowPath(zero ply, c, l, lʹ elib.Index) *ply {
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]ply, cNext, cNext)
		copy(q, *p)
		for i := c; i < cNext; i++ {
			q[i] = zero
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *ply_vec) Validate(i uint) *ply {
	var zero ply
	return p.validate(i+1, zero)
}

func (p *ply_vec) ValidateInit(i uint, zero ply) *ply {
	return p.validate(i+1, zero)
}

func (p *ply_vec) ValidateLen(l uint) (v *ply) {
	if l > 0 {
		var zero ply
		v = p.validate(l, zero)
	}
	return
}

func (p *ply_vec) ValidateLenInit(l uint, zero ply) (v *ply) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p ply_vec) Len() uint { return uint(len(p)) }
